### ISSUE TITLE
why DateTime compare fails?

### ISSUE THREAD

**Issue by bung87** [GULPF/timezones#1]
it without problem before I using `timezones` to parse tz info.
```
....
12:28 PM EST November 16, 2017==2017-11-16T12:28:00-05:00!=0001-00-00T00:00:00+00:00
12-Mar-19==0019-03-12T00:00:00Z!=0001-00-00T00:00:00+00:00
13-Nov-19==0019-11-13T00:00:00Z!=0001-00-00T00:00:00+00:00
1-Jul-15==0015-07-01T00:00:00Z!=0001-00-00T00:00:00+00:00
 March 23, 2019==2019-03-23T00:00:00Z!=0001-00-00T00:00:00+00:00
.....
[FAILED] all
Error: execution of an external program failed: '/Users/bung/nim_works/datetime_parse/tests/test1 '
     Error: Execution failed with exit code 256
        ... Command: "/Users/bung/.nimble/bin/nim" c --noNimblePath -d:NimblePkgVersion=0.1.0 --path:"/Users/bung/.nimble/pkgs/timezones-0.5.1" "-r" "--path:."  "/Users/bung/nim_works/datetime_parse/tests/test1"
```
https://github.com/bung87/datetime_parse/blob/master/tests/test1.nim

**Comment by GULPF** [comment]
I took a look and it seems like you have test failures that are unrelated to this package. For example, `Wednesday, August 21st 2019` fails but `Wednesday, August 21 2019` does not and I doubt it's caused by the timezone package. Please post a more reduced test case if you've found a bug in the timezone package.

**Comment by bung87** [comment]
`Wednesday, August 21 2019` that's make even weird,  this date time format not in my pattern so it will not parse correctly

**Comment by GULPF** [comment]
What I mean is that `Wednesday, August 21st 2019` (which is included in `corpus.txt`) fails to parse, but `Wednesday, August 21 2019` (which is not included in `corpus.txt`) does not fail to parse.

**Comment by bung87** [comment]
I dont have idea now , print outputs as expected , but the check not work as expected.

**Comment by bung87** [comment]
I fixed pattern to pass `Wednesday, August 21st 2019`, found there is `cst6cdt` and no `cst` makes one pattern not pass.
