### ISSUE TITLE
`nimble test` fails with the latest Nim

### ISSUE THREAD

**Issue by narimiran** [GULPF/timezones#2]
When trying to run `nimble test` locally, I get:

`timezones/posixtimezones.nim(398, 33) Error: can raise an unlisted exception: ref OSError`

----

When run on Nim's CI, the error message is:

```
tests\tests.nim(20, 61): Check failed: initDateTime(21, mOct, 2017, 1, 0, 0).format(f) == "2017-10-21 01:00 +02:00"
initDateTime(21, mOct, 2017, 1, 0, 0).format(f) was 2017-10-21 01:00 +00:00
[FAILED] dst edge cases
```

**Comment by GULPF** [comment]
Both these issues should now be fixed
