### ISSUE TITLE
Error during install using nim v1.2.0

### ISSUE THREAD

**Issue by hiteshjasani** [GULPF/timezones#4]
First off, thanks for a very helpful library!

I've set up github actions for testing and am seeing an issue with installing the library when referenced from a nimble file.  This install problem doesn't occur with other libs, only timezones.

To help diagnose, I created a minimal repo that reproduces the issue I'm seeing.  Look at the github actions tab to see the failures and the last passing case.

https://github.com/hiteshjasani/nim-timezones-testing-bug

```text
 Installing timezones@0.5.1
    Reading official package list
Downloading https://github.com/GULPF/timezones using git
    Cloning latest tagged version: v0.5.1
  Verifying dependencies for timezones@0.5.1
 Installing timezones@0.5.1
     Error: No binaries built, did you specify a valid binary name?
##[error]Process completed with exit code 1.
```

**Comment by GULPF** [comment]
Thanks for the bug report :) The latest release (v0.5.2) which works with latest Nim was not properly tagged, so nimble didn't find it. This should now be fixed

**Comment by hiteshjasani** [comment]
I changed the dep to 0.5.2 but see the same problem.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/6628/81449319-07a5bb80-914e-11ea-874f-022dc1a84248.png">

**Comment by GULPF** [comment]
Sorry, I assumed I had fixed the issue because `nimble install timezones` wasn't even working locally for me until I had fixed the tagging...

I forked your test repo and tried with another nimble package that install a binary (INim) and it fails as well: https://github.com/GULPF/nim-timezones-testing-bug/runs/657765733?check_suite_focus=true. This seems like a Nimble issue

**Comment by hiteshjasani** [comment]
Yes, this problem is indeed in nimble.  I've added a workaround to the test repo and filed an issue with nimble.  Feel free to close this issue.  Thanks.

https://github.com/nim-lang/nimble/issues/801
